=== AmandaBTCh/OpenDungeons/XML/xsd/ActorScheme.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2005/08/xml.xsd"/>      
    <xs:group name="Actor" >
        <xs:sequence>
            <xs:element name="actor">
                <xs:complexType>                    
                    <xs:sequence>                        
                        <xs:element name="class" type="xs:string"/>                        
                        <xs:element name="name"  type="xs:string"/>                        
                        <xs:element name="HP" type="xs:integer"/>                                        
                        <xs:element name="mana" type="xs:integer"/>                      
                        <xs:element name="posX" type="xs:integer"/>                        
                        <xs:element name="posY" type="xs:integer"/>                        
                        <xs:element name="posZ" type="xs:integer"/>                        
                        <xs:element name="color" type="xs:string"/>                        
                        <xs:element name="weaponLname" type="weapon"/>                        
                        <xs:element name="weaponRname" type="weapon"/>                        
                    </xs:sequence>
                    <xs:attribute ref="xml:base"/>      
                </xs:complexType>
                
            </xs:element>            
    </xs:sequence>  
    </xs:group> 


    <xs:element name="actor">
        <xs:complexType>                    
            <xs:sequence>                        
                <xs:element name="class" type="xs:string"/>                        
                <xs:element name="name"  type="xs:string"/>                        
                <xs:element name="HP" type="xs:integer"/>                                        
                <xs:element name="mana" type="xs:integer"/>                      
                <xs:element name="posX" type="xs:integer"/>                        
                <xs:element name="posY" type="xs:integer"/>                        
                <xs:element name="posZ" type="xs:integer"/>                        
                <xs:element name="color" type="xs:string"/>                        
                <xs:element name="weaponLname" type="weapon"/>                        
                <xs:element name="weaponRname" type="weapon"/>                        
            </xs:sequence>     
        </xs:complexType>
        
    </xs:element> 

    <xs:complexType name="weapon">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>           
            <xs:element name="damage" type="xs:integer"/>
            <xs:element name="range" type="xs:integer"/>
            <xs:element name="defense" type="xs:integer"/>

        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== AmandaBTCh/OpenDungeons/XML/Actors/Kre.xml
<?xml version="1.0" encoding="UTF-8"?>
<actor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xsd/ActorScheme.xsd">
    <class>Kreatur</class>
    <name>Kre</name>
    <HP>180</HP>
    <mana>10</mana>
    <posX>15</posX>
    <posY>16</posY>
    <posZ>0</posZ>
    <color>2</color>
    <weaponLname>
        <name>none</name>
        <damage>12</damage>
        <range>4</range>
        <defense>0</defense>
    </weaponLname>
    <weaponRname>
        <name>none</name>
        <damage>6</damage>
        <range>4</range>
        <defense>0</defense>
    </weaponRname>
</actor>

=== AmandaBTCh/OpenDungeons/XML/Actors/Knight.xml
<?xml version="1.0" encoding="UTF-8"?>
<actor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xsd/ActorScheme.xsd">
    <class>Knight</class>
    <name>Knight</name>
    <HP>155</HP>
    <mana>2</mana>
    <posX>-12</posX>
    <posY>-2</posY>
    <posZ>0</posZ>
    <color>1</color>
    <weaponLname>
        <name>none</name>
        <damage>8</damage>
        <range>4</range>
        <defense>0</defense>
    </weaponLname>
    <weaponRname>
        <name>Sabre</name>
        <damage>10</damage>
        <range>3</range>
        <defense>0</defense>
    </weaponRname>
</actor>

=== AmandaBTCh/OpenDungeons/XML/Actors/Knight_005.xml
<?xml version="1.0" encoding="UTF-8"?>
<actor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xsd/ActorScheme.xsd">
    <class>Knight</class>
    <name>Knight_005</name>
    <HP>155</HP>
    <mana>2</mana>
    <posX>29</posX>
    <posY>-62</posY>
    <posZ>0</posZ>
    <color>1</color>
    <weaponLname>
        <name>Roundshield</name>
        <damage>0</damage>
        <range>0</range>
        <defense>5</defense>
    </weaponLname>
    <weaponRname>
        <name>Longsword</name>
        <damage>14</damage>
        <range>3</range>
        <defense>0</defense>
    </weaponRname>
</actor>

=== AmandaBTCh/OpenDungeons/XML/Actors/Wiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<actor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xsd/ActorScheme.xsd">
    <class>Wizard</class>
    <name>Wiz</name>
    <HP>80</HP>
    <mana>50</mana>
    <posX>-7</posX>
    <posY>13</posY>
    <posZ>0</posZ>
    <color>1</color>
    <weaponLname>
        <name>Staff</name>
        <damage>7</damage>
        <range>9</range>
        <defense>0</defense>
    </weaponLname>
    <weaponRname>
        <name>none</name>
        <damage>8</damage>
        <range>3</range>
        <defense>0</defense>
    </weaponRname>
</actor>

=== AmandaBTCh/OpenDungeons/XML/Actors/Orc_0002.xml
<?xml version="1.0" encoding="UTF-8"?>
<actor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xsd/ActorScheme.xsd">
    <class>Orc</class>
    <name>Orc_0002</name>
    <HP>165</HP>
    <mana>10</mana>
    <posX>7</posX>
    <posY>12</posY>
    <posZ>0</posZ>
    <color>2</color>
    <weaponLname>
        <name>none</name>
        <damage>8</damage>
        <range>4</range>
        <defense>0</defense>
    </weaponLname>
    <weaponRname>
        <name>Longsword</name>
        <damage>14</damage>
        <range>4</range>
        <defense>0</defense>
    </weaponRname>
</actor>
