=== AmandaBTCh/OpenDungeons/XML/xsd/RoomScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2005/08/xml.xsd"/>    
    <xs:group name="Room" >
    <xs:sequence>
    <xs:element name="room">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="roomType" type="xs:string"/>
                <xs:element name="meshName" type="xs:string"/>
                <xs:element name="color" type="xs:string"/>
                <xs:element name="numTiles" type="xs:integer"/>
                <xs:element name="point"  minOccurs="1" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tileX" type="xs:integer"/>
                            <xs:element name="tileY" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="xml:base"/>   
        </xs:complexType>
    </xs:element>
    </xs:sequence>  
    </xs:group>    
<xs:element name="room">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="roomType" type="xs:string"/>
            <xs:element name="meshName" type="xs:string"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="numTiles" type="xs:integer"/>
            <xs:element name="point"  minOccurs="1" maxOccurs="unbounded" >
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="tileX" type="xs:integer"/>
                        <xs:element name="tileY" type="xs:integer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== AmandaBTCh/OpenDungeons/XML/Rooms/room_8.xml
<?xml version="1.0" encoding="UTF-8"?>
 <room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/RoomScheme.xsd">
<roomType>Forge</roomType>
<meshName>Forge</meshName>
<color>2</color>
<numTiles>16</numTiles>
<point>
<tileX>9</tileX>
<tileY>9</tileY>
</point>
<point>
<tileX>9</tileX>
<tileY>10</tileY>
</point>
<point>
<tileX>9</tileX>
<tileY>11</tileY>
</point>
<point>
<tileX>9</tileX>
<tileY>12</tileY>
</point>
<point>
<tileX>10</tileX>
<tileY>9</tileY>
</point>
<point>
<tileX>10</tileX>
<tileY>10</tileY>
</point>
<point>
<tileX>10</tileX>
<tileY>11</tileY>
</point>
<point>
<tileX>10</tileX>
<tileY>12</tileY>
</point>
<point>
<tileX>11</tileX>
<tileY>9</tileY>
</point>
<point>
<tileX>11</tileX>
<tileY>10</tileY>
</point>
<point>
<tileX>11</tileX>
<tileY>11</tileY>
</point>
<point>
<tileX>11</tileX>
<tileY>12</tileY>
</point>
<point>
<tileX>12</tileX>
<tileY>9</tileY>
</point>
<point>
<tileX>12</tileX>
<tileY>10</tileY>
</point>
<point>
<tileX>12</tileX>
<tileY>11</tileY>
</point>
<point>
<tileX>12</tileX>
<tileY>12</tileY>
</point>
</room>

=== AmandaBTCh/OpenDungeons/Xml5/room_2.xml
<?xml version="1.0" encoding="UTF-8"?>
 <room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/RoomScheme.xsd">
<roomType>Quarters</roomType>
<meshName>Quarters</meshName>
<color>1</color>
<numTiles>2</numTiles>
<pair>
<tileX>-5</tileX>
<tileY>13</tileY>
</pair>
<pair>
<tileX>-6</tileX>
<tileY>13</tileY>
</pair>
</room>

=== AmandaBTCh/OpenDungeons/Xml5/room_3.xml
<?xml version="1.0" encoding="UTF-8"?>
 <room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/RoomScheme.xsd">
<roomType>Treasury</roomType>
<meshName>Treasury</meshName>
<color>1</color>
<numTiles>1</numTiles>
<pair>
<tileX>-4</tileX>
<tileY>15</tileY>
</pair>
</room>
