=== AmandaBTCh/OpenDungeons/XML/xsd/SeatScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2005/08/xml.xsd"/>
    
    <xs:element name="Seat">   
        <xs:complexType >
            <xs:sequence>
                <xs:element name="color" type="xs:string"/>
                <xs:element name="faction" type="xs:string"/>
                <xs:element name="startingX" type="xs:integer"/>
                <xs:element name="startingY" type="xs:integer"/>
                <xs:element name="colorR" type="xs:decimal"/>            
                <xs:element name="colorG" type="xs:decimal"/>
                <xs:element name="colorB" type="xs:decimal"/>            
            </xs:sequence>
        </xs:complexType>
    </xs:element>    
    <xs:group name="Seat" >
        <xs:sequence>
            <xs:element name="Seat"  maxOccurs="1">                
                <xs:complexType >
                    <xs:sequence>
                        <xs:element name="color" type="xs:string"/>
                        <xs:element name="faction" type="xs:string"/>
                        <xs:element name="startingX" type="xs:integer"/>
                        <xs:element name="startingY" type="xs:integer"/>
                        <xs:element name="colorR" type="xs:decimal"/>            
                        <xs:element name="colorG" type="xs:decimal"/>
                        <xs:element name="colorB" type="xs:decimal"/>            
                    </xs:sequence>
                    <xs:attribute ref="xml:base"/>   
                </xs:complexType>
            </xs:element>        
        </xs:sequence>      
    </xs:group>
    


</xs:schema>

=== AmandaBTCh/OpenDungeons/Xml6/Seat_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Seat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/SeatScheme.xsd">
        <color>3</color>
        <faction>Villians</faction>
        <startingX>15</startingX>
        <startingY>0</startingY>
        <colorR>0</colorR>
        <colorG>0</colorG>
        <colorB>0.4</colorB>
 </Seat>

=== AmandaBTCh/OpenDungeons/Xml6/Seat_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<Seat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/SeatScheme.xsd">
        <color>5</color>
        <faction>Animals</faction>
        <startingX>15</startingX>
        <startingY>0</startingY>
        <colorR>0.4</colorR>
        <colorG>0.1</colorG>
        <colorB>0.4</colorB>
 </Seat>

=== AmandaBTCh/OpenDungeons/XML/Seats/Seat_0.xml
<Seat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/SeatScheme.xsd">
        <color>1</color>
        <faction>Undead</faction>
        <startingX>-5</startingX>
        <startingY>10</startingY>
        <colorR>0</colorR>
        <colorG>0.4</colorG>
        <colorB>0</colorB>
 </Seat>

=== AmandaBTCh/OpenDungeons/Xml6/Seat_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Seat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/SeatScheme.xsd">
        <color>2</color>
        <faction>Heroes</faction>
        <startingX>15</startingX>
        <startingY>0</startingY>
        <colorR>0.4</colorR>
        <colorG>0</colorG>
        <colorB>0</colorB>
</Seat>
