=== AmandaBTCh/OpenDungeons/xsd/CreatureSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="creature">
        <xs:complexType>

            <xs:sequence>

                <xs:element name="class" type="xs:string"/>

                <xs:element name="name"  type="xs:string"/>
                
                <xs:element name="HP" type="xs:integer"/>                
                
                <xs:element name="mana" type="xs:integer"/>
                
                <xs:element name="posX" type="xs:integer"/>

                <xs:element name="posY" type="xs:integer"/>

                <xs:element name="posZ" type="xs:integer"/>

                <xs:element name="color" type="xs:string"/>

                <xs:element name="weaponLname" type="weapon"/>

                <xs:element name="weaponRname" type="weapon"/>

            </xs:sequence>
        </xs:complexType>

    </xs:element>




    <xs:complexType name="weapon">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>           
            <xs:element name="damage" type="xs:integer"/>
            <xs:element name="range" type="xs:integer"/>
            <xs:element name="defense" type="xs:integer"/>

        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== AmandaBTCh/OpenDungeons/Xml/Dragon_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <name>Dragon_001</name>
    <HP>200 </HP>
    <mana>25 </mana>
    <posX>-41</posX>
    <posY>-92</posY>
    <posZ>0</posZ>
    <color>1</color>
    <weaponLname>
        <name>none</name>
        <damage>10</damage>
        <range>4</range>
        <defense>UniqueUniconr18</defense>
        
    </weaponLname>
    <weaponRname>
        <name>none</name>
        <damage>8</damage>
        <range>3</range>
        <defense>0</defense>
            
     </weaponRname>        
        
        
</creature>

=== AmandaBTCh/OpenDungeons/Xml/example_28.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <class>Knight</class>
    <name>Knight_003</name>
    <HP>155 </HP>
    <mana>2 </mana>
    <posX>-16</posX>
    <posY>1</posY>
    <posZ>0</posZ>
    <color>1</color>
    <weaponLname>
        <name>Shield_small</name>
        <damage>14</damage>
        <range>4</range>
        <defense>0</defense>
        
    </weaponLname>
    <weaponRname>
        <name>Longsword</name>
        <damage>14</damage>
        <range>3</range>
        <defense>0</defense>
            
     </weaponRname>        
        
        
</creature>

=== AmandaBTCh/OpenDungeons/Xml/Dwarf1_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <name>Dwarf1_001</name>
    <HP>145 </HP>
    <mana>7 </mana>
    <posX>7</posX>
    <posY>-7</posY>
    <posZ>0</posZ>
    <color>2</color>
    <weaponLname>
        <name>Roundshield</name>
        <damage>0</damage>
        <range>0</range>
        <defense>UniqueUniconr18</defense>
        
    </weaponLname>
    <weaponRname>
        <name>Sabre</name>
        <damage>10</damage>
        <range>3</range>
        <defense>0</defense>
            
     </weaponRname>        
        
        
</creature>

=== AmandaBTCh/OpenDungeons/Xml/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <name>UniqueUnicorn10</name>
    <HP>UniqueUnicorn23 </HP>
    <mana>UniqueUnicorn24 </mana>
    <posX>UniqueUnicorn11</posX>
    <posY>UniqueUnicorn12</posY>
    <posZ>UniqueUnicorn13</posZ>
    <color>UniqueUnicorn14</color>
    <weaponLname>
        <name>UniqueUnicorn15</name>
        <damage>UniqueUnicorn16</damage>
        <range>UniqueUnicorn17</range>
        <defense>UniqueUnicorn18</defense>
        
    </weaponLname>
    <weaponRname>
        <name>UniqueUnicorn19</name>
        <damage>UniqueUnicorn20</damage>
        <range>UniqueUnicorn21</range>
        <defense>UniqueUnicorn22</defense>
            
     </weaponRname>        
        
        
</creature>

=== AmandaBTCh/OpenDungeons/Xml/example_16.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <class>Kobold</class>
    <name>Kobold_012</name>
    <HP>125 </HP>
    <mana>3 </mana>
    <posX>-10</posX>
    <posY>-3</posY>
    <posZ>0</posZ>
    <color>1</color>
    <weaponLname>
        <name>Roundshield</name>
        <damage>0</damage>
        <range>0</range>
        <defense>5</defense>
        
    </weaponLname>
    <weaponRname>
        <name>Longsword</name>
        <damage>14</damage>
        <range>3</range>
        <defense>0</defense>
            
     </weaponRname>        
        
        
</creature>

=== AmandaBTCh/OpenDungeons/Xml/example_43.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <class>Dwarf2</class>
    <name>Dwarf2_002</name>
    <HP>145 </HP>
    <mana>7 </mana>
    <posX>2</posX>
    <posY>-9</posY>
    <posZ>0</posZ>
    <color>2</color>
    <weaponLname>
        <name>none</name>
        <damage>6</damage>
        <range>4</range>
        <defense>0</defense>
        
    </weaponLname>
    <weaponRname>
        <name>Longsword</name>
        <damage>14</damage>
        <range>4</range>
        <defense>0</defense>
            
     </weaponRname>        
        
        
</creature>

=== AmandaBTCh/OpenDungeons/Xml/Knight_007.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <name>Knight_007</name>
    <HP>155 </HP>
    <mana>2 </mana>
    <posX>-15</posX>
    <posY>2</posY>
    <posZ>0</posZ>
    <color>1</color>
    <weaponLname>
        <name>none</name>
        <damage>8</damage>
        <range>4</range>
        <defense>0</defense>
        
    </weaponLname>
    <weaponRname>
        <name>Sabre</name>
        <damage>10</damage>
        <range>3</range>
        <defense>0</defense>
            
     </weaponRname>        
        
        
</creature>

=== AmandaBTCh/OpenDungeons/XML/Actors/Wizard7.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/CreatureSchema.xsd">
    <name>Wizard7</name>
    <HP>125 </HP>
    <mana>3 </mana>
    <posX>-10</posX>
    <posY>28</posY>
    <posZ>0</posZ>
    <color>2</color>
    <weaponLname>
        <name>Staff</name>
        <damage>7</damage>
        <range>10</range>
        <defense>3</defense>
        
    </weaponLname>
    <weaponRname>
        <name>none</name>
        <damage>1</damage>
        <range>4</range>
        <defense>0</defense>
            
     </weaponRname>        
        
        
</creature>
