=== AmandaBTCh/OpenDungeons/xsd/LightScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Light">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Diffuse" type="RGB"/>
                <xs:element name="Specular" type="RGB"/>
                <xs:element name="Attenuation" type="AttenuationType"/>
            </xs:sequence>


        </xs:complexType>




    </xs:element>

    <xs:complexType name="RGB">

        <xs:sequence>
            <xs:element name="Red" type="xs:decimal"/>

            <xs:element name="Green" type="xs:decimal"/>

            <xs:element name="Blue" type="xs:decimal"/>



        </xs:sequence>

    </xs:complexType>


    <xs:complexType name="AttenuationType">
        <xs:sequence>
            <xs:element name="Range" type="xs:decimal"/>
            <xs:element name="Const" type="xs:decimal"/>
            <xs:element name="Linear" type="xs:decimal"/>
            <xs:element name="Quadraple" type="xs:decimal"/>


        </xs:sequence>

    </xs:complexType>







</xs:schema>

=== AmandaBTCh/OpenDungeons/XML/Lights/Light_20.xml
<?xml version="1.0" encoding="UTF-8"?>
<Light xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/LightScheme.xsd">
    <posX>1</posX>
    <posY>-16</posY>
    <posZ>3.75</posZ>
    <Diffuse>
        <Red>0.9</Red>
        <Green>0.9</Green>
        <Blue>0.9</Blue>
    </Diffuse>
    <Specular>
        <Red>0.6</Red>
        <Green>0.6</Green>
        <Blue>0.6</Blue>
    </Specular>
    <Attenuation>
        <Range>50</Range>
        <Const>0.005</Const>
        <Linear>0.25</Linear>
        <Quadraple>0.0013</Quadraple>
    </Attenuation>
</Light>

=== AmandaBTCh/OpenDungeons/Xml3/ExampleLight1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Light xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/LightScheme.xsd">
    <posX>UniqueUnicorn10</posX>
    <posY>UniqueUnicorn11</posY>
    <posZ>UniqueUnicorn12</posZ>
    <Diffuse>
        <Red>UniqueUnicorn13</Red>
        <Green>UniqueUnicorn14</Green>
        <Blue>UniqueUnicorn15</Blue>
    </Diffuse>
    <Specular>
        <Red>UniqueUnicorn16</Red>
        <Green>UniqueUnicorn17</Green>
        <Blue>UniqueUnicorn18</Blue>
    </Specular>
    <Attenuation>
        <Range>UniqueUnicorn19</Range>
        <Const>UniqueUnicorn20</Const>
        <Linear>UniqueUnicorn21</Linear>
        <Quadraple>UniqueUnicorn22</Quadraple>
    </Attenuation>
</Light>
