=== AmandaBTCh/OpenDungeons/xsd/SeatScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:group name="SeatList" >
        <xs:sequence>
            <xs:element name="Seat"  maxOccurs="unbounded">   
                <xs:complexType >
                    <xs:sequence>
                        <xs:element name="color" type="xs:string"/>
                        <xs:element name="faction" type="xs:string"/>
                        <xs:element name="startingX" type="xs:integer"/>
                        <xs:element name="startingY" type="xs:integer"/>
                        <xs:element name="colorR" type="xs:decimal"/>            
                        <xs:element name="colorG" type="xs:decimal"/>
                        <xs:element name="colorB" type="xs:decimal"/>            
                    </xs:sequence>
                </xs:complexType>
            </xs:element>        
        </xs:sequence>      
    </xs:group>
    <xs:element name="SeatList" >
        <xs:complexType >
        <xs:sequence maxOccurs="1">
            <xs:group ref="SeatList"/>
        </xs:sequence>
        </xs:complexType >
    </xs:element>  
</xs:schema>

=== AmandaBTCh/OpenDungeons/xsd/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<SeatList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/tom/Opendungeons/opendungeons/xsd/SeatScheme.xsd">
    <Seat>
        <color>Zl1wzKyQ</color>
        <faction>GhqbrRtSmGnL6</faction>
        <startingX>400891616</startingX>
        <startingY>-674884055</startingY>
        <colorR>147988419.71</colorR>
        <colorG>257847737.248</colorG>
        <colorB>836756474.102</colorB>
    </Seat>
    <Seat>
        <color>tP8.DOHSU07EwhMdqp5OAi6F7</color>
        <faction>NWXep1CVTaHKOraNMRWbFX</faction>
        <startingX>559180671</startingX>
        <startingY>1466276248</startingY>
        <colorR>1411269083.027</colorR>
        <colorG>1849639608.945</colorG>
        <colorB>650006790.36</colorB>
    </Seat>
    <Seat>
        <color>WHa-zmwbK</color>
        <faction>JypbI-_ng-G0XUthuY8dfvxXhv</faction>
        <startingX>-1731996240</startingX>
        <startingY>-2127622996</startingY>
        <colorR>1023271139.044</colorR>
        <colorG>1432965871.653</colorG>
        <colorB>1965662944.042</colorB>
    </Seat>
    <Seat>
        <color>dxIhLypTibi9YuWsM3hF97tQ0O</color>
        <faction>WCH3kGuTMJM_</faction>
        <startingX>-733871244</startingX>
        <startingY>744407533</startingY>
        <colorR>-700940675.611</colorR>
        <colorG>-823461732.024</colorG>
        <colorB>-122121414.721</colorB>
    </Seat>
    <Seat>
        <color>uJACN8Kz</color>
        <faction>apLNjLyecPyN2O</faction>
        <startingX>710520745</startingX>
        <startingY>-1785094772</startingY>
        <colorR>1973922773.52</colorR>
        <colorG>1297633546.274</colorG>
        <colorB>1326395572.612</colorB>
    </Seat>
</SeatList>
